### ISSUE TITLE
Support for private classes (e.g. Dayjs)

### ISSUE THREAD

**Issue by william0bra** [karmaniverous/serify-deserify#14]
Dayjs is kind of uneasy to work with because it does not expose its class. That way, I could not find a way to work with both libraries together.

**Comment by william0bra** [comment]
I just realized all I needed was to use the object's contructor name instead of the type.

const serifyOptions = {
  types: {
    'M': { // Dayjs
      serifier: (unserified: dayjs.Dayjs) => unserified.valueOf(),
      deserifier: (serified: number) => dayjs(serified),
    }
  }
}

**Comment by karmaniverous** [comment]
Ah yes that's smart! I don't know if you saw the [default options](https://github.com/karmaniverous/serify-deserify/blob/main/lib/options/defaultOptions.js) setup but I do substantially the same thing for Date.
